GameStore/ViewModels/Comment/AddCommentViewModel.cs
using GameStore.App_LocalResources;
using System;
using System.ComponentModel.DataAnnotations;

namespace GameStore.ViewModels.Comment
{
    public class AddCommentViewModel
    {
        [Required(ErrorMessageResourceName = "CommentNameRequired", ErrorMessageResourceType = typeof(GlobalRes))]
        [MaxLength(length: 25, ErrorMessageResourceName = "CommentNameMaxLen", ErrorMessageResourceType = typeof(GlobalRes))]
        [MinLength(length: 2, ErrorMessageResourceName = "CommentNameMaxLen", ErrorMessageResourceType = typeof(GlobalRes))]
        public string Name { get; set; }

        [Required]
        [RegularExpression(pattern: @"^[a-zA-Zа-яА-Я0-9,\.\!\?@()\|\/\\\[\]&\-;\s]+$", ErrorMessageResourceName = "СommentBodyRegex", ErrorMessageResourceType = typeof(GlobalRes))]
        [MaxLength(length: 500, ErrorMessageResourceName = "CommentBodyMaxlen", ErrorMessageResourceType = typeof(GlobalRes))]
        public string Body { get; set; }

        public Guid UserId { get; set; }

        public string Quote { get; set; }

        public string GameKey { get; set; }

        public Guid? ParentId { get; set; }
    }
}

GameStore/ViewModels/Comment/BanViewModel.cs
using GameStore.App_LocalResources;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace GameStore.ViewModels.Comment
{
    public class BanViewModel
    {
        [Required(ErrorMessageResourceName = "BanDurationRequired", ErrorMessageResourceType = typeof(GlobalRes))]
        public string BanDuration { get; set; }

        public IEnumerable<ListItem<string>> BanDurations { get; set; }
        public ListItem<string> SelectedBan { get; set; }
    }
}

GameStore/ViewModels/Comment/CommentViewModel.cs
using GameStore.App_LocalResources;
using System;
using System.ComponentModel.DataAnnotations;

namespace GameStore.ViewModels.Comment
{
    public class CommentViewModel
    {
        [Required]
        public Guid IdGuid { get; set; }

        [Required]
        public int CommentId { get; set; }

        [Required(ErrorMessageResourceName = "CommentAuthorRequired", ErrorMessageResourceType = typeof(GlobalRes))]
        public string AuthorName { get; set; }

        [Required(ErrorMessageResourceName = "CommentBodyRequired", ErrorMessageResourceType = typeof(GlobalRes))]
        public string Body { get; set; }

        [Required(ErrorMessageResourceName = "CommentQuoteRequired", ErrorMessageResourceType = typeof(GlobalRes))]
        public string Quote { get; set; }

        [Required]
        public string AnswerId { get; set; }

        [Required(ErrorMessageResourceName = "CommentParentAuthorRequired", ErrorMessageResourceType = typeof(GlobalRes))]
        public string ParentCommentAuthorName { get; set; }

        [Required(ErrorMessageResourceName = "СommentDateRequired", ErrorMessageResourceType = typeof(GlobalRes))]
        public DateTime CommentDate { get; set; }

        public Guid UserId { get; set; }

        [Required]
        public int CommentLevel { get; set; }

        [Required]
        public string GameKey { get; set; }
    }
}

GameStore/Controllers/CommentController.cs
using AutoMapper;
using GameStore.BLL.Abstract;
using GameStore.Common;
using GameStore.Common.Helpers;
using GameStore.DTO;
using GameStore.Helpers;
using GameStore.Helpers.EnumExtentions;
using GameStore.ViewModels;
using GameStore.ViewModels.Comment;
using System;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace GameStore.Controllers
{
    public class CommentController : BaseController
    {
        private readonly ICommentService _commentService;
        private readonly IGameService _gameService;

        public CommentController(ICommentService service, IGameService gameService)
        {
            this._commentService = service;
            this._gameService = gameService;
        }

        [HttpPost]
        public ActionResult NewComment(AddCommentViewModel comment)
        {
            if (ModelState.IsValid)
            {
                var commentDto = Mapper.Map<CommentDto>(comment);

                Response.StatusCode = (int)HttpStatusCode.OK;
                var full = new FullCommentsViewModel();

                var addcomment = new AddCommentViewModel() { GameKey = comment.GameKey };

                _commentService.AddComment(commentDto, comment.GameKey);

                var game = _gameService.GetGame(comment.GameKey);

                full.AddCommentViewModel = addcomment;
                full.GameKey = comment.GameKey;
                full.Comments = CommentHelper.GetCommentViewFromDto(game.Comments.Where(x => !x.IsDeleted && x.ParentId == null));
                return PartialView("_Comments", full);
            }

            Response.StatusCode = (int)HttpStatusCode.BadRequest;
            var fullCommentsViewModel = new FullCommentsViewModel();
            fullCommentsViewModel.AddCommentViewModel = comment;
            fullCommentsViewModel.GameKey = comment.GameKey;
            fullCommentsViewModel.Comments = CommentHelper.GetCommentViewFromDto(_gameService.GetGame(comment.GameKey).Comments.Where(x => !x.IsDeleted && x.ParentId == null));
            return PartialView("_Comments", fullCommentsViewModel);
        }

        [HttpPost]
        [Authorize(Roles = "Manager,Moderator")]
        public ActionResult Delete(Guid id, string gameKey)
        {
            var comment = _commentService.GetComment(id);
            if (comment == null || string.IsNullOrEmpty(gameKey))
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                throw new Exception($"Bad request for deleting comment occured id = {id} and gameKey = {gameKey}");
            }

            _commentService.DeleteComment(id);
            var game = _gameService.GetGame(comment.GameKey);

            Response.StatusCode = (int)HttpStatusCode.OK;
            var full = new FullCommentsViewModel();

            var addcomment = new AddCommentViewModel() { GameKey = game.Key };

            full.AddCommentViewModel = addcomment;
            full.GameKey = game.Key;
            full.Comments = CommentHelper.GetCommentViewFromDto(_gameService.GetGame(game.Key).Comments.Where(x => !x.IsDeleted && x.ParentId == null));
            return PartialView("_Comments", full);
        }

        [HttpGet]
        [Authorize(Roles = "Manager,Moderator")]
        public ActionResult Ban(Guid id)
        {
            var newId = 0;
            var banDurations = BanDuration.Day.GetAllValuesOfEnum<BanDuration>().Select(x => new ListItem<string>() { Id = newId++, Item = x.GetLocalizedDescription(), Value = x.ConvertToString() });
            var banView = new BanViewModel() { BanDurations = banDurations };
            return View(banView);
        }

        [HttpPost]
        [Authorize(Roles = "Manager,Moderator")]
        public ActionResult Ban(BanViewModel ban)
        {
            if (ModelState.IsValid)
            {
                return View("BanSuccess");
            }
            return View(ban);
        }

        [HttpGet]
        public ActionResult Comments(String key)
        {
            if (key == null)
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Json(HttpStatusCode.BadRequest);
            }

            var comments = _commentService.GetComments(key);
            if (comments == null)
            {
                Response.StatusCode = (int)HttpStatusCode.NotFound;
                return Json(HttpStatusCode.NotFound);
            }

            Response.StatusCode = (int)HttpStatusCode.OK;
            return Json(comments, JsonRequestBehavior.AllowGet);
        }
    }
}

GameStore/Controllers/GameController.cs
using AutoMapper;
using GameStore.BLL.Abstract;
using GameStore.Common;
using GameStore.Common.Helpers;
using GameStore.DTO;
using GameStore.Helpers;
using GameStore.Helpers.EnumExtentions;
using GameStore.Helpers.LocalizationHelpers;
using GameStore.ViewModels;
using GameStore.ViewModels.Comment;
using GameStore.ViewModels.Game;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mime;
using System.Threading;
using System.Web.Mvc;
using System.Web.UI;

namespace GameStore.Controllers
{
    public class GameController : BaseController
    {
        private readonly IGameService _gameService;
        private readonly IGenreService _genreService;
        private readonly IPlatformService _platformService;
        private readonly IPublisherService _publisherService;

        public GameController(IGameService service, IPlatformService platform, IGenreService genre, IPublisherService publisher)
        {
            this._gameService = service;

            this._genreService = genre;

            this._platformService = platform;

            this._publisherService = publisher;
        }

        // GET: Game
        [HttpGet]
        [OutputCache(Duration = 60, VaryByParam = "none", Location = OutputCacheLocation.Client, NoStore = true)]
        public ActionResult Index(FilterViewModel filter = null, int[] genres = null, int[] publishers = null, int[] platforms = null, int? date = null)
        {
            var gamesModel = new GamesViewModel();

            if (filter.PriceLow.HasValue && filter.PriceLow.Value < 0)
            {
                ModelState.AddModelError("PriceLow", "Low bound of price should be greater zero");
            }

            if (filter.PriceHigh.HasValue && filter.PriceHigh.Value < 0)
            {
                ModelState.AddModelError("PriceHigh", "High bound of price should be greater zero");
            }

            if (filter.PriceLow.HasValue && filter.PriceHigh.HasValue && filter.PriceHigh.Value < filter.PriceLow.Value)
            {
                ModelState.AddModelError("PriceHigh", "High bound of price should be greater than low bound of price");
            }

            if (filter.NumberOnPage == null && genres == null && publishers == null && platforms == null)
            {
                filter = GetDefaultFilter();
            }
            else
            {
                filter = UpdateFilterDefaultValues(filter);
                filter.SelectedGenres = genres?.ToList();
                filter.SelectedPlatforms = platforms?.ToList();
                filter.SelectedPublishers = publishers?.ToList();
                filter.SelectedGenres = genres?.ToList();
                filter.Date = filter.DateFilterTypes.FirstOrDefault(x => x.Id == (date ?? 0)).Value;

                var dateFilterIndex = filter.DateFilterTypes.FirstOrDefault(x => x.Value == filter.Date)?.Id;

                if (date != null)
                {
                    filter.SelectedFilterTypes = new List<int>() { dateFilterIndex.Value };
                }
            }

            gamesModel.TotalGamesCount = _gameService.GetAllGamesCount();

            var filterDto = FilterViewModelToFilterDtoConvertor.Convert(filter, gamesModel.TotalGamesCount);

            gamesModel.TotalGamesCount = _gameService.GetCountOfFilteredGames(filterDto);

            filterDto = FilterViewModelToFilterDtoConvertor.Convert(filter, gamesModel.TotalGamesCount);

            var games =
                Mapper.Map<IEnumerable<GameDto>, IEnumerable<SimpleGameViewModel>>(
                    _gameService.GetFilteredGames(filterDto).ToList());
            if (games != null)
            {
                Response.StatusCode = (int)HttpStatusCode.OK;

                if (filter.NumberOnPage != null && filter.NumberOnPage != "All")
                {
                    gamesModel.NumberOnPage = int.Parse(filter.NumberOnPage);
                }
                else
                {
                    gamesModel.NumberOnPage = gamesModel.TotalGamesCount;
                }

                gamesModel.Games = games;
                gamesModel.Filter = filter;
                return View(gamesModel);
            }

            gamesModel.Filter = filter;
            gamesModel.Games = new List<SimpleGameViewModel>();

            Response.StatusCode = (int)HttpStatusCode.NotFound;
            return View(gamesModel);
        }

        [HttpGet]
        [Authorize(Roles = "Manager")]
        public ActionResult Update(string key)
        {
            ViewBag.DefaultLanguage = Thread.CurrentThread.LanguageFromThread();
            var game = _gameService.GetGame(key);
            var model = Mapper.Map<EditGameViewModel>(game);

            model.GameLocalization = EntitiesLocalizatorHelper.GetLocalizationGame(model.GameLocalization);

            var genres = _genreService.GetAllGenres().Select(x => x.Name);
            var platforms = _platformService.GetAllPlatforms().Select(x => x.Type.GetLocalizedDescription());
            var publishers = _publisherService.GetAllPublishers().Select(x => x.Name);

            var selGenres = new List<ListItem<string>>();
            var selPlatf = new List<ListItem<string>>();
            foreach (var item in model.SelectedGenreIds)
            {
                selGenres.Add(new ListItem<string>() { Item = item, Value = item });
            }

            foreach (var item in model.SelectedPlatformTypeIds)
            {
                selPlatf.Add(new ListItem<string>() { Item = item, Value = item });
            }
            model.SelectedPlatforms = selPlatf;
            model.SelectedGenres = selGenres;

            var i = 0;

            var genreList = new List<ListItem<string>>();
            foreach (var item in genres.ToList())
            {
                genreList.Add(new ListItem<string>() { Id = i++, Item = item, Value = item });
            }
            model.Genres = genreList;
            i = 0;

            var platformList = new List<ListItem<string>>();
            foreach (var item in platforms.ToList())
            {
                platformList.Add(new ListItem<string>() { Id = i++, Item = item, Value = item });
            }
            model.PlatformTypes = platformList;
            i = 0;

            var publisherNamesList = new List<ListItem<string>>();
            foreach (var item in publishers.ToList())
            {
                publisherNamesList.Add(new ListItem<string>() { Id = i++, Item = item, Value = item });
            }
            model.PublisherNames = publisherNamesList;

            ViewData["PublisherNameId"] = model.PublisherNames.First(x => x.Item == game.PublisherName).Id;

            foreach (var selectedGenre in model.SelectedGenres)
            {
                selectedGenre.Id = model.Genres.First(x => x.Item == selectedGenre.Item).Id;
            }

            foreach (var selectedPlatform in model.SelectedPlatforms)
            {
                selectedPlatform.Id = model.PlatformTypes.First(x => x.Item == selectedPlatform.Item).Id;
            }

            return View(model);
        }

        [HttpPost]
        [OutputCache(Duration = 60, Location = OutputCacheLocation.Client, NoStore = true)]
        public ActionResult GetGamesCount()
        {
            var count = _gameService.GetAllGamesCount();
            return Json(new { success = true, count = count });
        }

        [HttpPost]
        [Authorize(Roles = "Manager")]
        [OutputCache(Duration = 60, VaryByParam = "game", Location = OutputCacheLocation.Client, NoStore = true)]
        public ActionResult Update(EditGameViewModel game)
        {
            if (ModelState.IsValid)
            {
                var gameDTO = Mapper.Map<GameDto>(game);
                _gameService.UpdateGame(gameDTO);
                Response.StatusCode = (int)HttpStatusCode.OK;
                return RedirectToAction("Index");
            }
            Response.StatusCode = (int)HttpStatusCode.BadRequest;

            ViewBag.DefaultLanguage = Thread.CurrentThread.LanguageFromThread();

            var genres = _genreService.GetAllGenres().Select(x => x.Name);
            var platforms = _platformService.GetAllPlatforms().Select(x => x.Type.GetLocalizedDescription());
            var publishers = _publisherService.GetAllPublishers().Select(x => x.Name);

            var selGenres = new List<ListItem<string>>();
            var selPlatf = new List<ListItem<string>>();
            foreach (var item in game.SelectedGenreIds)
            {
                selGenres.Add(new ListItem<string>() { Item = item, Value = item });
            }

            foreach (var item in game.SelectedPlatformTypeIds)
            {
                selPlatf.Add(new ListItem<string>() { Item = item, Value = item });
            }
            game.SelectedPlatforms = selPlatf;
            game.SelectedGenres = selGenres;
            var i = 0;

            var genreList = new List<ListItem<string>>();
            foreach (var item in genres.ToList())
            {
                genreList.Add(new ListItem<string>() { Id = i++, Item = item, Value = item });
            }
            game.Genres = genreList;
            i = 0;

            var platformList = new List<ListItem<string>>();
            foreach (var item in platforms.ToList())
            {
                platformList.Add(new ListItem<string>() { Id = i++, Item = item, Value = item });
            }
            game.PlatformTypes = platformList;
            i = 0;

            var publisherNamesList = new List<ListItem<string>>();
            foreach (var item in publishers.ToList())
            {
                publisherNamesList.Add(new ListItem<string>() { Id = i++, Item = item, Value = item });
            }
            game.PublisherNames = publisherNamesList;

GameStore/Views/Shared/_AddComment.cshtml
@model GameStore.ViewModels.Comment.AddCommentViewModel

<div id="addcomment" class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @using (Ajax.BeginForm("NewComment", "Comment", new AjaxOptions()
            {
                HttpMethod = "POST",
                InsertionMode = InsertionMode.Replace,
                UpdateTargetId = "comments"
            }))
            {
                <div class="form-group">
                    @Html.LabelFor(x => x.Quote, GlobalRes.CommentQuote + ":", new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextAreaFor(model => model.Quote, new { id = "addcomment-quote", @class = "form-control", @readonly = "true" })
                    </div>
                </div>

                @Html.HiddenFor(model => model.GameKey)

                @Html.HiddenFor(model => model.ParentId, new { id = "addcomment-answer" })
                <div class="form-group">
                    @Html.LabelFor(model => model.Name, GlobalRes.CommentName + ":", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <input type="text" value="@User.Identity.Name" class="form-control" id="addcomment-name" readonly="readonly" name="Name" />
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Body, GlobalRes.CommentBody + ":", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextAreaFor(model => model.Body, htmlAttributes: new { @class = "form-control", rows = "5", cols = "15", id = "addcomment-body" })
                        @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="@GlobalRes.SendBtn" class="btn btn-default" />
                    </div>
                </div>
            }
        </div>
    </div>
</div>

GameStore/Views/Shared/_Comment.cshtml
@model GameStore.ViewModels.Comment.CommentViewModel

<div class="comment comment-offset-@Model.CommentLevel" id="comment-@Model.CommentId">
    <div class="comment-head">
        <div class="hidden" id="idguid-@Model.CommentId">@Model.IdGuid</div>
        <p class="comment-author">@Model.AuthorName</p>
        <small class="comment-date">@Model.CommentDate</small>
    </div>
    <div class="comment-body">
        <input type="hidden" id="comment-gameKey-@Model.CommentId" value="@Model.GameKey" />
        @if (!string.IsNullOrEmpty(Model.ParentCommentAuthorName))
            {
            <div class="comment-answer-to">
                <strong class="comment-answer-label">@GlobalRes.ParentCommentAuthorName:</strong><strong class="comment-answer-name">@Model.ParentCommentAuthorName</strong>
                <a href="#@Model.AnswerId" class="comment-answer-to-btn">@GlobalRes.ParentCommentAuthorName @Model.ParentCommentAuthorName</a>
            </div>
        }

        @if (!string.IsNullOrEmpty(Model.Quote))
            {
            <blockquote class="comment-quote">
                @Model.Quote
            </blockquote>
        }
        <p class="comment-body-text" id="comment-body-@Model.CommentId">@Model.Body</p>
    </div>

    <div class="comment-buttons">
        <div class="btn btn-info btn-answer" id="answer-btn-@Model.CommentId">@GlobalRes.AnswerBtn</div>
        <div class="btn btn-success btn-quote" id="quote-btn-@Model.CommentId">@GlobalRes.CommentQuote</div>
        @if (!User.IsInRole("Guest"))
            {
            <div class="btn btn-default btn-delete-comment" id="btnDeleteComment-@Model.CommentId">@GlobalRes.DeleteBtn</div>
            if (User.IsInRole("Moderator"))
            {
                <div class="btn btn-danger">@Html.ActionLink(GlobalRes.BanBtn, "Ban", new { controller = "comment", action = "Ban", id = Model.IdGuid, lang = GlobalRes.CurrentLang })</div>
            }
        }
    </div>
</div>

GameStore/Views/Shared/_Comments.cshtml
@model GameStore.ViewModels.Comment.FullCommentsViewModel

<div class="container-fluid" id ="comments">
    <div class="row">
            <div class="col-md-12">
                @{ Html.RenderPartial("_AddComment", Model.AddCommentViewModel); }
            </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            @foreach (var comment in Model.Comments)
            {
                Html.RenderPartial("_Comment", comment);
            }
        </div>
        @if (User.IsInRole("Moderator"))
        {
            <div id="deleteModalBlock">
                @{ Html.RenderPartial("_Delete"); }
            </div>
        }
    </div>
</div>

GameStore/Views/Shared/_Delete.cshtml
<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">@GlobalRes.DeleteCommentTitle</h4>
            </div>
            <div class="modal-body">
                @GlobalRes.DeleteCommentText
                <input type="hidden" id="deleteCommentGuid" />
                <input type="hidden" id="deleteCommentGameKey" />
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" id ="deleteModalCancel">@GlobalRes.CancelBtn</button>
                <button type="button" class="btn btn-primary" id = "deleteModalDelete">@GlobalRes.DeleteBtn</button>
            </div>
        </div>
    </div>
</div>

GameStore/Views/Shared/_Layout.cshtml
@using GameStore.Helpers.LocalizationHelpers
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - @GlobalRes.SiteName</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/comment.css" rel="stylesheet" type="text/css" />
    @Styles.Render("~/styles/jqueryui")
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryui")
    <script src="~/scripts/bootstrap.min.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="@Url.Action("Index", "Game")" class="navbar-brand">@GlobalRes.SiteName</a></li>
                    <li><a>@GlobalRes.TitleGames: <span id="gamecount"></span></a></li>
                    <li><a href="@Url.Action("Index", "Publisher")">@GlobalRes.PublisherIndexTitle</a></li>
                    @if (!User.IsInRole("Guest"))
                    {
                        <li><a href="@Url.Action("Index", "Basket")">@GlobalRes.BasketBtn</a></li>
                    }
                    <li><a href="@Url.Action("Index", "Genre")">@GlobalRes.GenresTitle</a></li>
                    @if (User.IsInRole("Administrator"))
                    {
                        <li><a href="@Url.Action("Index", "User")">@GlobalRes.UsersTitle</a></li>
                    }
                    <li><a href="@Url.Action("History", new {controller = "Basket", action = "history"})">@GlobalRes.TitleHistory</a></li>
                    @if (User.IsInRole("manager"))
                    {
                        <li><a href="@Url.Action("Orders", new {controller = "Basket", action = "Orders", lang = GlobalRes.CurrentLang})">@GlobalRes.TitleOrders</a></li>
                    }
                    <li class="navbar-form">@Html.LanguageDropdown()</li>
                    @Html.Action("UserLogin", "Account")
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - @GlobalRes.SiteName</p>
        </footer>
    </div>
<script src="~/scripts/getGamesCount.js"></script>
<script src="~/scripts/languageSwitch.js"></script>
    
    @RenderSection("datepicker", false)

</body>
</html>